/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tracnghiem.view;

import com.formdev.flatlaf.FlatClientProperties;
import com.tracnghiem.bus.LogBUS;
import com.tracnghiem.bus.UserBUS;
import com.tracnghiem.dto.UserDTO;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author huulu
 */
public class loginView extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    private UserBUS userBUS = new UserBUS();
    private LogBUS logBUS = new LogBUS();

    public loginView() {

        initComponents();
        username_field.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Tên đăng nhập");
        password_field.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Mật khẩu");
        password_field.putClientProperty(FlatClientProperties.STYLE, ""
                + "showRevealButton:true;" + "showCapsLock:true;");

        setLocationRelativeTo(null);
    }

    private void login() {

        String username = username_field.getText();
        String password = new String(password_field.getPassword());

        // Kiểm tra Username và Password
        if (username.trim().trim().isEmpty()) {
            setErrorBorder(username_field);
        } else if (password.trim().isEmpty()) {
            setErrorBorder(password_field);
        } else {

            UserDTO user = userBUS.login(username, password);
            if (user != null) {
                if (user.getIsAdmin() == 1) {
                    new mainView(user).setVisible(true); // Mở giao diện Admin

                } else {
                    new userView(user).setVisible(true); //   Mở giao diện User
                    logBUS.saveLog(user.getUserFullName() + " Đăng nhập.", user.getUserID(), "");
                }
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu không đúng!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        username_field = new javax.swing.JTextField();
        password_field = new javax.swing.JPasswordField();
        submit_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kiểm Tra Trắc Nghiệm");
        setResizable(false);

        jPanel1.setBackground( Color.decode("#f5f5f5")

        );
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        title.setForeground(Color.decode("#0094ff")
        );
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Đăng nhập");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 380, 90));

        username_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                username_fieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                username_fieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                username_fieldKeyTyped(evt);
            }
        });
        jPanel1.add(username_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 300, 50));

        password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_fieldActionPerformed(evt);
            }
        });
        password_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_fieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                password_fieldKeyTyped(evt);
            }
        });
        jPanel1.add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 300, 50));

        submit_btn.setBackground(Color.decode("#0094ff")
        );
        submit_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        submit_btn.setText("ĐĂNG NHẬP");
        submit_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(submit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 300, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_fieldActionPerformed

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed

        login();

    }//GEN-LAST:event_submit_btnActionPerformed

    private void username_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_fieldKeyTyped
        resetBorder(username_field);

    }//GEN-LAST:event_username_fieldKeyTyped

    private void password_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_fieldKeyTyped
        resetBorder(password_field);
    }//GEN-LAST:event_password_fieldKeyTyped

    private void username_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_fieldKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_username_fieldKeyPressed

    private void username_fieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_fieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_username_fieldKeyReleased

    private void password_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_fieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // Thực hiện hành động mong muốn ở đây...
            login();
        }
    }//GEN-LAST:event_password_fieldKeyPressed

    // Đặt viền đỏ khi có lỗi
    private static void setErrorBorder(JComponent component) {
        component.putClientProperty(FlatClientProperties.OUTLINE, "error");
    }

    // Reset viền về mặc định khi hợp lệ
    private static void resetBorder(JComponent component) {
        component.putClientProperty(FlatClientProperties.OUTLINE, null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JButton submit_btn;
    private javax.swing.JLabel title;
    private javax.swing.JTextField username_field;
    // End of variables declaration//GEN-END:variables
}
