/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.tracnghiem.view;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.tracnghiem.dto.UserDTO;
import com.tracnghiem.view.panel.BaiThiPanel;
import com.tracnghiem.view.panel.Info;
import com.tracnghiem.view.panel.XemDiemPanel;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author huulu
 */
public class userView extends javax.swing.JFrame {

    /**
     * Creates new form userView
     */
    private static CardLayout cardLayout;
    private Info info;
    private BaiThiPanel baiThiPanel;
    private XemDiemPanel xemDiemPanel;
    private final UserDTO user;

    public userView(UserDTO user) {
        initComponents();
        this.user = user;
        xemDiemPanel = new XemDiemPanel(user);
        baiThiPanel = new BaiThiPanel(user);
        info = new Info(user);
        
        String[] tName =  user.getUserFullName().split(" "); 
        name. setText(tName[tName.length - 1]);
        
        cardLayout = (CardLayout) main_panel.getLayout();
        //Menu
        List<JPanel> menuList = List.of(menu1, menu2, menu3, menu4);
        menu_panel.putClientProperty(FlatClientProperties.STYLE, "arc: 40; background: #eaeaea");

        for (JPanel menu : menuList) {
            menu.putClientProperty("selected", false);
            addHoverEffect(menu, menuList);
        }

        main_panel.add(info, "thongtin");
        main_panel.add(xemDiemPanel, "xemdiem");
        main_panel.add(baiThiPanel, "kiemtra");

        //Hien thi mac dinh
        menu2.putClientProperty(FlatClientProperties.STYLE, "arc: 20; background: #033d67");
        menu2.putClientProperty("selected", true);
        cardLayout.show(main_panel, menu2.getName());

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        left_panel1 = new javax.swing.JPanel();
        head1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        menu_panel = new javax.swing.JPanel();
        menu1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        menu2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        menu3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        menu4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        main_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setBackground(new Color(0xeaeaea));

        left_panel1.setMaximumSize(new java.awt.Dimension(180, 32767));
        left_panel1.setPreferredSize(new java.awt.Dimension(180, 750));

        head1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new FlatSVGIcon("icons/user.svg", 40, 40
        )
    );

    name.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
    name.setText("User");

    javax.swing.GroupLayout head1Layout = new javax.swing.GroupLayout(head1);
    head1.setLayout(head1Layout);
    head1Layout.setHorizontalGroup(
        head1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(head1Layout.createSequentialGroup()
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    head1Layout.setVerticalGroup(
        head1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(head1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(head1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    menu_panel.setPreferredSize(new java.awt.Dimension(168, 637));
    menu_panel.setLayout(new javax.swing.BoxLayout(menu_panel, javax.swing.BoxLayout.Y_AXIS));

    menu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    menu1.setMaximumSize(new java.awt.Dimension(168, 47));
    menu1.setPreferredSize(new java.awt.Dimension(168, 47));
    menu_panel.add(Box.createVerticalStrut(0));
    menu1.setName("thongtin");

    jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
    jLabel5.setText("Thông Tin");
    jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
    jLabel6.setIcon(new FlatSVGIcon("icons/table-of-contents.svg", 30, 30
    )
    );
    jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel6.setPreferredSize(new java.awt.Dimension(35, 35));

    javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
    menu1.setLayout(menu1Layout);
    menu1Layout.setHorizontalGroup(
        menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(menu1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    menu1Layout.setVerticalGroup(
        menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(menu1Layout.createSequentialGroup()
            .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menu1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(menu1Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    menu_panel.add(menu1);

    menu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    menu2.setMaximumSize(new java.awt.Dimension(168, 47));
    menu2.setPreferredSize(new java.awt.Dimension(168, 47));
    menu_panel.add(Box.createVerticalStrut(10));
    menu2.setName("kiemtra");

    jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
    jLabel11.setForeground(new java.awt.Color(255, 255, 255));
    jLabel11.setText("Kiểm Tra");
    jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    jLabel12.setForeground(new java.awt.Color(255, 255, 255));
    jLabel12.setIcon(new FlatSVGIcon("icons/table-of-contents.svg", 30, 30
    )
    );
    jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel12.setPreferredSize(new java.awt.Dimension(35, 35));

    javax.swing.GroupLayout menu2Layout = new javax.swing.GroupLayout(menu2);
    menu2.setLayout(menu2Layout);
    menu2Layout.setHorizontalGroup(
        menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(menu2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    menu2Layout.setVerticalGroup(
        menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(menu2Layout.createSequentialGroup()
            .addGroup(menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menu2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(menu2Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    menu_panel.add(menu2);

    menu3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    menu3.setMaximumSize(new java.awt.Dimension(168, 47));
    menu3.setPreferredSize(new java.awt.Dimension(168, 47));
    menu_panel.add(Box.createVerticalStrut(10));
    menu3.setName("xemdiem");

    jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
    jLabel13.setForeground(new java.awt.Color(255, 255, 255));
    jLabel13.setText("Xem Điểm");
    jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    jLabel14.setForeground(new java.awt.Color(255, 255, 255));
    jLabel14.setIcon(new FlatSVGIcon("icons/table-of-contents.svg", 30, 30
    )
    );
    jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel14.setPreferredSize(new java.awt.Dimension(35, 35));

    javax.swing.GroupLayout menu3Layout = new javax.swing.GroupLayout(menu3);
    menu3.setLayout(menu3Layout);
    menu3Layout.setHorizontalGroup(
        menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(menu3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    menu3Layout.setVerticalGroup(
        menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(menu3Layout.createSequentialGroup()
            .addGroup(menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menu3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(menu3Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    menu_panel.add(menu3);

    menu4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    menu4.setMaximumSize(new java.awt.Dimension(168, 47));
    menu4.setPreferredSize(new java.awt.Dimension(168, 47));
    menu_panel.add(Box.createVerticalGlue());
    menu_panel.add(Box.createRigidArea(new Dimension(0, 10)));
    menu4.setName("dangxuat");

    jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
    jLabel15.setForeground(new java.awt.Color(255, 255, 255));
    jLabel15.setText("Đăng Xuất");
    jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    jLabel16.setForeground(new java.awt.Color(255, 255, 255));
    jLabel16.setIcon(new FlatSVGIcon("icons/logout.svg", 30, 30
    )
    );
    jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel16.setPreferredSize(new java.awt.Dimension(35, 35));

    javax.swing.GroupLayout menu4Layout = new javax.swing.GroupLayout(menu4);
    menu4.setLayout(menu4Layout);
    menu4Layout.setHorizontalGroup(
        menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(menu4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    menu4Layout.setVerticalGroup(
        menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(menu4Layout.createSequentialGroup()
            .addGroup(menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menu4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(menu4Layout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    menu_panel.add(menu4);

    javax.swing.GroupLayout left_panel1Layout = new javax.swing.GroupLayout(left_panel1);
    left_panel1.setLayout(left_panel1Layout);
    left_panel1Layout.setHorizontalGroup(
        left_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, left_panel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(left_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(menu_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(head1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
            .addContainerGap())
    );
    left_panel1Layout.setVerticalGroup(
        left_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(left_panel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(head1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(menu_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(12, Short.MAX_VALUE))
    );

    main_panel.setLayout(new java.awt.CardLayout());

    javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
    main.setLayout(mainLayout);
    mainLayout.setHorizontalGroup(
        mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(mainLayout.createSequentialGroup()
            .addComponent(left_panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE))
    );
    mainLayout.setVerticalGroup(
        mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(left_panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addHoverEffect(JPanel menu, List<JPanel> allMenus) {
        String defaultStyle = "arc: 20; background: #005b91";
        String hoverStyle = "arc: 20; background: #033d67";
        String selectedStyle = "arc: 20; background: #033d67";

        menu.putClientProperty(FlatClientProperties.STYLE, defaultStyle);

        menu.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (!menu.getClientProperty("selected").equals(true)) {
                    menu.putClientProperty(FlatClientProperties.STYLE, hoverStyle);
                }
            }

            @Override
            public void mouseExited(MouseEvent e) {
                if (!menu.getClientProperty("selected").equals(true)) {
                    menu.putClientProperty(FlatClientProperties.STYLE, defaultStyle);
                }
            }

            @Override
            public void mouseClicked(MouseEvent e) {
                if (SwingUtilities.isLeftMouseButton(e)) {
                    for (JPanel otherMenu : allMenus) {
                        otherMenu.putClientProperty(FlatClientProperties.STYLE, defaultStyle);
                        otherMenu.putClientProperty("selected", false);
                    }
                    // Giữ màu menu được chọn
                    menu.putClientProperty(FlatClientProperties.STYLE, selectedStyle);
                    menu.putClientProperty("selected", true);
                    if (!menu.getName().equals("dangxuat")) {
                        JPanel newPanel;
                        switch (menu.getName()) {
                            case "thongtin":
                                newPanel = new Info(user);
                                break;
                            case "kiemtra":
                                newPanel = new BaiThiPanel(user);
                                break;
                            case "xemdiem":
                                newPanel = new XemDiemPanel(user);
                                break;
                            default:
                                return;
                        }

                        main_panel.removeAll(); // Xóa tất cả panel cũ
                        main_panel.add(newPanel, menu.getName()); // Thêm panel mới
                        main_panel.revalidate();
                        main_panel.repaint();
                        cardLayout.show(main_panel, menu.getName());
                    } else {
                        if ((int) showLogoutDialog() == JOptionPane.YES_OPTION) {
                            //tro ve dang nhap
                            new loginView().setVisible(true);
                            dispose();
                            //
                        }
                    }

                }
            }
        }
        );
    }

    private static int showLogoutDialog() {
        JPanel panel = new JPanel();
        panel.setSize(300, 200);
        panel.add(new JLabel("Bạn có chắc chắn muốn đăng xuất không?"));
        Object[] options = {"Đăng xuất", "Hủy"};
        UIManager.put("OptionPane.yesButtonText", "Xác nhận");
        UIManager.put("OptionPane.noButtonText", "Hủy");
        int result = JOptionPane.showOptionDialog(
                null,
                "Bạn có chắc chắn muốn đăng xuất?",
                "Xác nhận đăng xuất",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE,
                null,
                options,
                options[1]
        );
        return result;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel head1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel left_panel1;
    private javax.swing.JPanel main;
    private javax.swing.JPanel main_panel;
    private javax.swing.JPanel menu1;
    private javax.swing.JPanel menu2;
    private javax.swing.JPanel menu3;
    private javax.swing.JPanel menu4;
    private javax.swing.JPanel menu_panel;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
