/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tracnghiem.view.components;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.tracnghiem.bus.TopicBUS;
import com.tracnghiem.dto.TopicDTO;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author X
 */
public class addTest extends javax.swing.JPanel {
    
    private final TopicBUS tBUS = new TopicBUS();
    private int idTopicSelected = -1;
    private final Map<String, Integer> topicMapParent = new LinkedHashMap<>();
    private final Map<String, Integer> topicMapChildren = new LinkedHashMap<>();
    private final Map<String, Integer> topicMapChildren1 = new LinkedHashMap<>();
    /**
     * Creates new form addTest
     */
    public addTest() {
        initComponents();
        
        
        loadTpParent(tBUS.getAllParent());
        
    }
    
    
    private void loadTpParent(ArrayList<TopicDTO> list) {
        topicMapParent.clear();
        topicMapParent.put("--None--", -1);

        for (TopicDTO t : list) {
            topicMapParent.put(t.getTpTitle(), t.getTpID());
        }

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        for (String s : topicMapParent.keySet()) {
            model.addElement(s);
        }
        cbbNhom.setModel(model);
    }
    private void loadTpChild1(int idParent) {
        topicMapChildren1.clear();
        topicMapChildren1.put("--None--", -1);

        ArrayList<TopicDTO> list = tBUS.getChildTopics(idParent);

        for (TopicDTO t : list) {
            topicMapChildren1.put(t.getTpTitle(), t.getTpID());
        }

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (String s : topicMapChildren1.keySet()) {
            model.addElement(s);
        }
        cbbBaiHoc.setModel(model);
        cbbBaiHoc.setSelectedIndex(0);
        
       
    }

    private void loadTpChild(int idParent) {
        topicMapChildren.clear();
        topicMapChildren.put("--None--", -1);
        
        ArrayList<TopicDTO> list = tBUS.getChildTopics(idParent);

        for (TopicDTO t : list) {
            topicMapChildren.put(t.getTpTitle(), t.getTpID());
        }

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (String s : topicMapChildren.keySet()) {
            model.addElement(s);
        }
        cbbChuDe.setModel(model);
        cbbChuDe.setSelectedIndex(0);
        loadTpChild1(-1);
    }
    
    // DocumentFilter để chặn ký tự không phải số
    static class NumericDocumentFilter extends DocumentFilter {
        @Override
        public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
            if (string.matches("\\d+")) { // Chỉ chấp nhận số (\\d+)
                super.insertString(fb, offset, string, attr);
            }
        }

        @Override
        public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
            if (text.matches("\\d+")) { // Chỉ chấp nhận số (\\d+)
                super.replace(fb, offset, length, text, attrs);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        luu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        madethi = new javax.swing.JTextField();
        tieude = new javax.swing.JTextField();
        cbbNhom = new javax.swing.JComboBox<>();
        ngaythi = new com.toedter.calendar.JDateChooser();
        giolam = new javax.swing.JTextField();
        luotlam = new javax.swing.JTextField();
        slKho = new javax.swing.JTextField();
        slTB = new javax.swing.JTextField();
        slD = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbbChuDe = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cbbBaiHoc = new javax.swing.JComboBox<>();

        luu.putClientProperty(FlatClientProperties.STYLE, "arc: 10; background: #0bae1d; foreground: #ffffff;");
        luu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        luu.setIcon(new FlatSVGIcon("icons/save.svg", 30, 30)
        );
        luu.setText("Lưu");
        luu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setText("ID");

        id.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        id.setText("NULL");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setText("Mã đề thi");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel7.setText("Tiêu đề");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setText("Nhóm");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel9.setText("Ngày thi");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel10.setText("Giờ làm( phút)");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel11.setText("Lượt làm");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel12.setText("SL Khó");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel14.setText("SL Dễ");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel15.setText("SL Trung");

        madethi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madethiActionPerformed(evt);
            }
        });

        tieude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tieudeActionPerformed(evt);
            }
        });

        cbbNhom.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Danh sách chủ đề");
        cbbNhom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbNhomActionPerformed(evt);
            }
        });

        giolam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giolamActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel13.setText("Chủ đề");

        cbbChuDe.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Danh sách chủ đề");
        cbbChuDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbChuDeActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel16.setText("Bài học");

        cbbBaiHoc.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Danh sách chủ đề");
        cbbBaiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbBaiHocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel13)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)))
                .addComponent(id)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(madethi, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel16))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tieude)
                                    .addComponent(cbbNhom, javax.swing.GroupLayout.Alignment.TRAILING, 0, 159, Short.MAX_VALUE)
                                    .addComponent(cbbChuDe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbbBaiHoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(luotlam))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel9))
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(slTB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slD, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ngaythi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(giolam, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slKho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(luu)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(luu)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(giolam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(madethi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel12)
                                    .addComponent(slKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tieude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel15)
                                    .addComponent(slTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(slD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ngaythi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbbNhom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbbChuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(cbbBaiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16))))))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(luotlam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        madethi.putClientProperty(FlatClientProperties.STYLE, "arc: 10; ");
        tieude.putClientProperty(FlatClientProperties.STYLE, "arc: 10; ");
        ngaythi.setDateFormatString("dd/MM/yyyy");
        ngaythi.getDateEditor().setEnabled(false);
        ngaythi.putClientProperty(FlatClientProperties.STYLE, "arc: 10; ");
        ((AbstractDocument) giolam.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        giolam.putClientProperty(FlatClientProperties.STYLE, "arc: 10; ");
        ((AbstractDocument) luotlam.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        luotlam.putClientProperty(FlatClientProperties.STYLE, "arc: 10; ");
        ((AbstractDocument) slKho.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        slKho.putClientProperty(FlatClientProperties.STYLE, "arc: 10; ");
        ((AbstractDocument) slTB.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        slTB.putClientProperty(FlatClientProperties.STYLE, "arc: 10; ");
        ((AbstractDocument) slD.getDocument()).setDocumentFilter(new NumericDocumentFilter());
        slD.putClientProperty(FlatClientProperties.STYLE, "arc: 10; ");
        cbbChuDe.addItem("--None--");
        cbbChuDe.setSelectedIndex(0);
        cbbBaiHoc.addItem("--None--");
        cbbBaiHoc.setSelectedIndex(0);
    }// </editor-fold>//GEN-END:initComponents

    private void luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
            null, "Bạn có muốn lưu dữ liệu không?", "Xác nhận lưu",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE
        );

        if (confirm == JOptionPane.YES_OPTION) {
          
        }
    }//GEN-LAST:event_luuActionPerformed

    private void tieudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tieudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tieudeActionPerformed

    private void cbbNhomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbNhomActionPerformed
       String selectedTopic = (String) cbbNhom.getSelectedItem();
        Integer selectedID = topicMapParent.get(selectedTopic);
        // Kiểm tra nếu selectedID là null thì không làm gì cả
        if (selectedID == null) {
            return;
        }
        loadTpChild(selectedID);
        idTopicSelected = selectedID;
    }//GEN-LAST:event_cbbNhomActionPerformed

    private void madethiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madethiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_madethiActionPerformed

    private void cbbChuDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbChuDeActionPerformed
        // TODO add your handling code here:

        String selectedTopic = (String) cbbChuDe.getSelectedItem();
        Integer selectedID = topicMapChildren.get(selectedTopic);
        // Kiểm tra nếu selectedID là null thì không làm gì cả
        if (selectedID == null) {
            return;
        }
        idTopicSelected = selectedID;
        loadTpChild1(selectedID);
        cbbBaiHoc.setSelectedIndex(0);

    }//GEN-LAST:event_cbbChuDeActionPerformed

    private void cbbBaiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbBaiHocActionPerformed
        // TODO add your handling code here:
        String selectedTopic = (String) cbbBaiHoc.getSelectedItem();
        Integer selectedID = topicMapChildren1.get(selectedTopic);
        // Kiểm tra nếu selectedID là null thì không làm gì cả
        if (selectedID == null) {
            return;
        }
        idTopicSelected = selectedID;
    }//GEN-LAST:event_cbbBaiHocActionPerformed

    private void giolamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giolamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giolamActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbBaiHoc;
    private javax.swing.JComboBox<String> cbbChuDe;
    private javax.swing.JComboBox<String> cbbNhom;
    private javax.swing.JTextField giolam;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField luotlam;
    private javax.swing.JButton luu;
    private javax.swing.JTextField madethi;
    private com.toedter.calendar.JDateChooser ngaythi;
    private javax.swing.JTextField slD;
    private javax.swing.JTextField slKho;
    private javax.swing.JTextField slTB;
    private javax.swing.JTextField tieude;
    // End of variables declaration//GEN-END:variables
}
