/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tracnghiem.view.components;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.tracnghiem.bus.AnswerBUS;
import com.tracnghiem.bus.QuestionBUS;
import com.tracnghiem.bus.ResultBUS;
import com.tracnghiem.bus.TestStructureBUS;
import com.tracnghiem.bus.TopicBUS;
import com.tracnghiem.bus.UserBUS;
import com.tracnghiem.dto.AnswerDTO;
import com.tracnghiem.dto.QuestionDTO;
import com.tracnghiem.dto.ResultDTO;
import com.tracnghiem.dto.TestStructureDTO;
import com.tracnghiem.dto.TopicDTO;
import com.tracnghiem.dto.UserDTO;
import com.tracnghiem.utils.UploadUtil;
import java.awt.BorderLayout;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import java.io.File;
import java.io.FileInputStream;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author huulu
 */
public class detailExam extends javax.swing.JPanel {

    private final TopicBUS tBUS = new TopicBUS();
    private final UserBUS uBUS = new UserBUS();
    private final ResultBUS rBUS = new ResultBUS();

    private String exCode;

    private ArrayList<UserDTO> listU = new ArrayList<>();
    private ArrayList<ResultDTO> listR = new ArrayList<>();

    /**
     * Creates new form addQuestion
     *
     * @param exCode
     */
    public detailExam(String exCode, boolean update) {
        initComponents();

        this.exCode = exCode;
        this.listR = rBUS.findAllByExCode(exCode);

//        for (ResultDTO r : listR) {
//            listU.add(uBUS.findOne(r.getUserID()));
//        }
        loadTable(listR);
    }

//    public detailExam(ArrayList<UserDTO> listU, boolean update) {
//        initComponents();
//        
//        this.listU = listU;
//        
//        loadTable(listU);
//
//    }
    private void setColumnWidthsForTable() {
        TableColumnModel columnModel = jTable1.getColumnModel();
        int totalWidth = jTable1.getWidth(); // Lấy chiều rộng tổng của bảng

        
        System.out.println("check: " + totalWidth);
        
        double[] columnRatios = {0.1, 0.5, 0.1, 0.1, 0.1};

        for (int i = 0; i < columnRatios.length; i++) {
            int columnWidth = (int) (totalWidth * columnRatios[i]);
            columnModel.getColumn(i).setPreferredWidth(columnWidth);
        }
    }

    private void loadTable(ArrayList<ResultDTO> list) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Xóa dữ liệu cũ

        if (list.isEmpty()) {
            model.addRow(new Object[]{"", "Không có dữ liệu", "", ""});
            return;
        }

        for (ResultDTO r : list) {
            model.addRow(new Object[]{
                r.getUserID(),
                uBUS.findOne(r.getUserID()).getUserFullName(),
                r.getRsNum(),
                getRightAns(r.getRsAnswer()) + "/" +  getTotalQues(r.getRsAnswer()),
                r.getRsMark()
            });
            
        }

    }

    private int getTotalQues(String answers) {
        return (int)Math.ceil(1.0* answers.split(";").length / 2);
    }
    
    private int getRightAns(String answers) {
        int rs = 0;
        String[] listA = answers.split(";");
        for (int i = 1; i < listA.length ; i+=2) {
            
            
            AnswerBUS aBUS = new AnswerBUS();
            if (aBUS.findOne(Integer.parseInt(listA[i].trim())).isIsRight()) {
                rs++;
            }
        }
        
        return rs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "ID", "Họ tên","Lượt làm", "Câu đúng", "Điểm"}

        ) {
            boolean[] canEdit = new boolean [] {
                false, false,false, false, false,
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        SwingUtilities.invokeLater(() -> setColumnWidthsForTable());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
