/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tracnghiem.view.components;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.tracnghiem.dto.AnswerDTO;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;

/**
 *
 * @author X
 */
public class previewDetailQuestion extends javax.swing.JPanel {
    ArrayList<AnswerDTO> listA = new ArrayList<>();
    private final ArrayList<JTextArea> listTextArea = new ArrayList<>();
    private final ArrayList<JRadioButton> listRBtn = new ArrayList<>();
    private final ArrayList<JLabel> listLabel = new ArrayList<>();
    private final ArrayList<JPanel> listPanel = new ArrayList<>();
    /**
     * Creates new form previewDetailQuestion
     * @param listA
     */
        public previewDetailQuestion(ArrayList<AnswerDTO> listA) {
        initComponents();
        
        listTextArea.add(dapanA);
        listTextArea.add(dapanB);
        listTextArea.add(dapanC);
        listTextArea.add(dapanD);
        listTextArea.add(dapanE);
        
        listLabel.add(hinhA);
        listLabel.add(hinhB);
        listLabel.add(hinhC);
        listLabel.add(hinhD);
        listLabel.add(hinhE);
        
        listRBtn.add(jRadioButton1);
        listRBtn.add(jRadioButton2);
        listRBtn.add(jRadioButton3);
        listRBtn.add(jRadioButton4);
        listRBtn.add(jRadioButton5);
        
        listPanel.add(panelA);
        listPanel.add(panelB);
        listPanel.add(panelC);
        listPanel.add(panelD);
        listPanel.add(panelE);
        
        this.listA = listA;
        
        loadPreviewAnswer();
    }

    
    private void loadPreviewAnswer() {
        for (int i = 0; i < listA.size(); i++) {
            listTextArea.get(i).setText(listA.get(i).getAwContent());
            listRBtn.get(i).setSelected(listA.get(i).isIsRight());
            if (listA.get(i).isIsRight()) {
                List<JPanel> panels = Arrays.asList(panelA, panelB, panelC, panelD, panelE);
                resetPanelColors(panels);  // Đặt lại màu tất cả panel trước khi đổi màu
                listPanel.get(i).putClientProperty(FlatClientProperties.STYLE, "arc: 10; background: #aaf697;");
            }
            listLabel.get(i).setText(listA.get(i).getAwPicture());
        }
    }
    private void resetPanelColors(List<JPanel> panels) {
        for (JPanel panel : panels) {
            panel.putClientProperty(FlatClientProperties.STYLE, "arc: 10;");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        panelA = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dapanA = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        hinhA = new javax.swing.JLabel();
        panelB = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dapanB = new javax.swing.JTextArea();
        jRadioButton2 = new javax.swing.JRadioButton();
        hinhB = new javax.swing.JLabel();
        panelC = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        dapanC = new javax.swing.JTextArea();
        jRadioButton3 = new javax.swing.JRadioButton();
        hinhC = new javax.swing.JLabel();
        panelD = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        dapanD = new javax.swing.JTextArea();
        jRadioButton4 = new javax.swing.JRadioButton();
        hinhD = new javax.swing.JLabel();
        panelE = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        dapanE = new javax.swing.JTextArea();
        jRadioButton5 = new javax.swing.JRadioButton();
        hinhE = new javax.swing.JLabel();

        jPanel3.putClientProperty(FlatClientProperties.STYLE, "arc: 10; background: #ffffff");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Đáp án:");

        panelA.putClientProperty(FlatClientProperties.STYLE, "arc: 10;");
        panelA.setPreferredSize(new java.awt.Dimension(810, 60));
        panelA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Câu A:");
        panelA.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 2, -1, -1));

        dapanA.setColumns(20);
        dapanA.setRows(5);
        jScrollPane2.setViewportView(dapanA);
        dapanA.setEnabled(false);

        panelA.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 540, 36));

        jRadioButton1.setText("Đáp án đúng");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        panelA.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 1, -1, -1));
        jRadioButton1.setEnabled(false);

        hinhA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelA.add(hinhA, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 40, 252, -1));

        panelB.putClientProperty(FlatClientProperties.STYLE, "arc: 10;");
        panelB.setPreferredSize(new java.awt.Dimension(810, 60));
        panelB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Câu B:");
        panelB.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 2, -1, -1));

        dapanB.setColumns(20);
        dapanB.setRows(5);
        jScrollPane3.setViewportView(dapanB);
        dapanB.setEnabled(false);

        panelB.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 540, 36));

        jRadioButton2.setText("Đáp án đúng");
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        panelB.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 1, -1, -1));
        jRadioButton2.setEnabled(false);

        hinhB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelB.add(hinhB, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 40, 252, -1));

        panelC.putClientProperty(FlatClientProperties.STYLE, "arc: 10;");
        panelC.setPreferredSize(new java.awt.Dimension(810, 60));
        panelC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Câu C:");
        panelC.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 2, -1, -1));

        dapanC.setColumns(20);
        dapanC.setRows(5);
        jScrollPane4.setViewportView(dapanC);
        dapanC.setEnabled(false);

        panelC.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 540, 36));

        jRadioButton3.setText("Đáp án đúng");
        jRadioButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        panelC.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 1, -1, -1));
        jRadioButton3.setEnabled(false);

        hinhC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelC.add(hinhC, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 40, 252, -1));

        panelD.putClientProperty(FlatClientProperties.STYLE, "arc: 10;");
        panelD.setPreferredSize(new java.awt.Dimension(810, 60));
        panelD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Câu D:");
        panelD.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 2, -1, -1));

        dapanD.setColumns(20);
        dapanD.setRows(5);
        jScrollPane5.setViewportView(dapanD);
        dapanD.setEnabled(false);

        panelD.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 540, 36));

        jRadioButton4.setText("Đáp án đúng");
        jRadioButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        panelD.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 1, -1, -1));
        jRadioButton4.setEnabled(false);

        hinhD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelD.add(hinhD, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 40, 252, -1));

        panelE.putClientProperty(FlatClientProperties.STYLE, "arc: 10;");
        panelE.setPreferredSize(new java.awt.Dimension(810, 60));
        panelE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Câu E:");
        panelE.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 2, -1, -1));

        dapanE.setColumns(20);
        dapanE.setRows(5);
        jScrollPane6.setViewportView(dapanE);
        dapanE.setEnabled(false);

        panelE.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 540, 36));

        jRadioButton5.setText("Đáp án đúng");
        jRadioButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        panelE.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 1, -1, -1));
        jRadioButton5.setEnabled(false);

        hinhE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelE.add(hinhE, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 40, 252, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 925, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dapanA;
    private javax.swing.JTextArea dapanB;
    private javax.swing.JTextArea dapanC;
    private javax.swing.JTextArea dapanD;
    private javax.swing.JTextArea dapanE;
    private javax.swing.JLabel hinhA;
    private javax.swing.JLabel hinhB;
    private javax.swing.JLabel hinhC;
    private javax.swing.JLabel hinhD;
    private javax.swing.JLabel hinhE;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel panelA;
    private javax.swing.JPanel panelB;
    private javax.swing.JPanel panelC;
    private javax.swing.JPanel panelD;
    private javax.swing.JPanel panelE;
    // End of variables declaration//GEN-END:variables
}
