/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.tracnghiem.view.components;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.tracnghiem.bus.AnswerBUS;
import com.tracnghiem.bus.QuestionBUS;
import com.tracnghiem.bus.TopicBUS;
import com.tracnghiem.dto.AnswerDTO;
import com.tracnghiem.dto.QuestionDTO;
import com.tracnghiem.dto.TopicDTO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.UIManager;

/**
 *
 * @author huulu
 */
public class detailQuestion extends javax.swing.JPanel {

    private int qID;
    private final QuestionBUS qBUS = new QuestionBUS();
    private final TopicBUS tBUS = new TopicBUS();
    private final AnswerBUS aBUS = new AnswerBUS();
    private final ArrayList<JTextArea> listTextArea = new ArrayList<>();
    private final ArrayList<JRadioButton> listRBtn = new ArrayList<>();
    private final ArrayList<JLabel> listLabel = new ArrayList<>();
    private final ArrayList<JPanel> listPanel = new ArrayList<>();
    
    private QuestionDTO question;
    private ArrayList<AnswerDTO> listAnswer = new ArrayList<>();
    /**
     * Creates new form addQuestion
     */
    public detailQuestion() {
        initComponents();
        ButtonGroup group = new ButtonGroup();
//        selectedButton(group);
        
    }
    public detailQuestion(int qID) {
        this.qID = qID;
        initComponents();
//        ButtonGroup group = new ButtonGroup();
//        selectedButton(group);
        
        listTextArea.add(dapanA);
        listTextArea.add(dapanB);
        listTextArea.add(dapanC);
        listTextArea.add(dapanD);
        listTextArea.add(dapanE);
        
        listLabel.add(hinhA);
        listLabel.add(hinhB);
        listLabel.add(hinhC);
        listLabel.add(hinhD);
        listLabel.add(hinhE);
        
        listRBtn.add(jRadioButton1);
        listRBtn.add(jRadioButton2);
        listRBtn.add(jRadioButton3);
        listRBtn.add(jRadioButton4);
        listRBtn.add(jRadioButton5);
        
        listPanel.add(panelA);
        listPanel.add(panelB);
        listPanel.add(panelC);
        listPanel.add(panelD);
        listPanel.add(panelE);
        
        
        
        loadDetailQuestion();
        
        
        
    }
     public detailQuestion(QuestionDTO question, ArrayList<AnswerDTO> listAnswer) {
        this.question = question;
        this.listAnswer = listAnswer;
        
        initComponents();
//        ButtonGroup group = new ButtonGroup();
//        selectedButton(group);
        
        listTextArea.add(dapanA);
        listTextArea.add(dapanB);
        listTextArea.add(dapanC);
        listTextArea.add(dapanD);
        listTextArea.add(dapanE);
        
        listLabel.add(hinhA);
        listLabel.add(hinhB);
        listLabel.add(hinhC);
        listLabel.add(hinhD);
        listLabel.add(hinhE);
        
        listRBtn.add(jRadioButton1);
        listRBtn.add(jRadioButton2);
        listRBtn.add(jRadioButton3);
        listRBtn.add(jRadioButton4);
        listRBtn.add(jRadioButton5);
        
        listPanel.add(panelA);
        listPanel.add(panelB);
        listPanel.add(panelC);
        listPanel.add(panelD);
        listPanel.add(panelE);
        
        
        
        loadDetailQuestion1();
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        monhocCBB = new javax.swing.JComboBox<>();
        chudeCBB = new javax.swing.JComboBox<>();
        baihocCBB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        macauhoi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noidung = new javax.swing.JTextArea();
        anh = new javax.swing.JPanel();
        qAnh = new javax.swing.JLabel();
        tenhinh = new javax.swing.JLabel();
        baihocCBB2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        panelA = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dapanA = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        hinhA = new javax.swing.JLabel();
        panelB = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dapanB = new javax.swing.JTextArea();
        jButton8 = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        hinhB = new javax.swing.JLabel();
        panelC = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        dapanC = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        hinhC = new javax.swing.JLabel();
        panelD = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        dapanD = new javax.swing.JTextArea();
        jButton10 = new javax.swing.JButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        hinhD = new javax.swing.JLabel();
        panelE = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        dapanE = new javax.swing.JTextArea();
        jButton11 = new javax.swing.JButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        hinhE = new javax.swing.JLabel();

        jPanel1.putClientProperty(FlatClientProperties.STYLE, "arc: 10; background: #ffffff");

        monhocCBB.setToolTipText("");
        monhocCBB.setName(""); // NOI18N

        baihocCBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baihocCBBActionPerformed(evt);
            }
        });

        jLabel1.setText("Môn học");

        jLabel2.setText("Chủ đề");

        jLabel3.setText("Bài học");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monhocCBB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chudeCBB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(baihocCBB, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monhocCBB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chudeCBB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baihocCBB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel2.putClientProperty(FlatClientProperties.STYLE, "arc: 10; background: #ffffff");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Mã câu hỏi:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Nội dung câu hỏi:");

        jButton6.putClientProperty(FlatClientProperties.STYLE, "arc: 10; background: #3276c3; foreground: #ffffff;");
        jButton6.setIcon(new FlatSVGIcon("icons/img-upload.svg", 20, 20)
        );
        jButton6.setText("Xem ảnh");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        macauhoi.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        macauhoi.setText("NULL");

        noidung.setColumns(20);
        noidung.setRows(5);
        jScrollPane1.setViewportView(noidung);
        noidung.setEnabled(false);

        javax.swing.GroupLayout anhLayout = new javax.swing.GroupLayout(anh);
        anh.setLayout(anhLayout);
        anhLayout.setHorizontalGroup(
            anhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(qAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        anhLayout.setVerticalGroup(
            anhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(qAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
        );

        tenhinh.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tenhinh.setText("NULL");

        baihocCBB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baihocCBB2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Độ khó:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Hình ảnh:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(macauhoi)))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(baihocCBB2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tenhinh, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6))
                            .addComponent(jLabel8))))
                .addGap(18, 18, 18)
                .addComponent(anh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(anh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(macauhoi))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jButton6)
                            .addComponent(tenhinh)
                            .addComponent(baihocCBB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        jPanel3.putClientProperty(FlatClientProperties.STYLE, "arc: 10; background: #ffffff");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Đáp án:");

        panelA.putClientProperty(FlatClientProperties.STYLE, "arc: 10;");
        panelA.setPreferredSize(new java.awt.Dimension(810, 60));
        panelA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Câu A:");
        panelA.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 2, -1, -1));

        dapanA.setColumns(20);
        dapanA.setRows(5);
        jScrollPane2.setViewportView(dapanA);
        dapanA.setEnabled(false);

        panelA.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 540, 36));

        jButton7.putClientProperty(FlatClientProperties.STYLE, "arc: 10; background: #3276c3; foreground: #ffffff;");
        jButton7.setIcon(new FlatSVGIcon("icons/img-upload.svg", 20, 20)
        );
        jButton7.setText("Xem ảnh");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panelA.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 34, -1, -1));

        jRadioButton1.setText("Đáp án đúng");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        panelA.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 1, -1, -1));
        jRadioButton1.setEnabled(false);

        hinhA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelA.add(hinhA, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 40, 252, -1));

        panelB.putClientProperty(FlatClientProperties.STYLE, "arc: 10;");
        panelB.setPreferredSize(new java.awt.Dimension(810, 60));
        panelB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Câu B:");
        panelB.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 2, -1, -1));

        dapanB.setColumns(20);
        dapanB.setRows(5);
        jScrollPane3.setViewportView(dapanB);
        dapanB.setEnabled(false);

        panelB.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 540, 36));

        jButton8.putClientProperty(FlatClientProperties.STYLE, "arc: 10; background: #3276c3; foreground: #ffffff;");
        jButton8.setIcon(new FlatSVGIcon("icons/img-upload.svg", 20, 20)
        );
        jButton8.setText("Xem ảnh");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panelB.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 34, -1, -1));

        jRadioButton2.setText("Đáp án đúng");
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        panelB.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 1, -1, -1));
        jRadioButton2.setEnabled(false);

        hinhB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelB.add(hinhB, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 40, 252, -1));

        panelC.putClientProperty(FlatClientProperties.STYLE, "arc: 10;");
        panelC.setPreferredSize(new java.awt.Dimension(810, 60));
        panelC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Câu C:");
        panelC.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 2, -1, -1));

        dapanC.setColumns(20);
        dapanC.setRows(5);
        jScrollPane4.setViewportView(dapanC);
        dapanC.setEnabled(false);

        panelC.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 540, 36));

        jButton9.putClientProperty(FlatClientProperties.STYLE, "arc: 10; background: #3276c3; foreground: #ffffff;");
        jButton9.setIcon(new FlatSVGIcon("icons/img-upload.svg", 20, 20)
        );
        jButton9.setText("Xem ảnh");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        panelC.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 34, -1, -1));

        jRadioButton3.setText("Đáp án đúng");
        jRadioButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        panelC.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 1, -1, -1));
        jRadioButton3.setEnabled(false);

        hinhC.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelC.add(hinhC, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 40, 252, -1));

        panelD.putClientProperty(FlatClientProperties.STYLE, "arc: 10;");
        panelD.setPreferredSize(new java.awt.Dimension(810, 60));
        panelD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Câu D:");
        panelD.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 2, -1, -1));

        dapanD.setColumns(20);
        dapanD.setRows(5);
        jScrollPane5.setViewportView(dapanD);
        dapanD.setEnabled(false);

        panelD.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 540, 36));

        jButton10.putClientProperty(FlatClientProperties.STYLE, "arc: 10; background: #3276c3; foreground: #ffffff;");
        jButton10.setIcon(new FlatSVGIcon("icons/img-upload.svg", 20, 20)
        );
        jButton10.setText("Xem ảnh");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        panelD.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 34, -1, -1));

        jRadioButton4.setText("Đáp án đúng");
        jRadioButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        panelD.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 1, -1, -1));
        jRadioButton4.setEnabled(false);

        hinhD.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelD.add(hinhD, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 40, 252, -1));

        panelE.putClientProperty(FlatClientProperties.STYLE, "arc: 10;");
        panelE.setPreferredSize(new java.awt.Dimension(810, 60));
        panelE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Câu E:");
        panelE.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 2, -1, -1));

        dapanE.setColumns(20);
        dapanE.setRows(5);
        jScrollPane6.setViewportView(dapanE);
        dapanE.setEnabled(false);

        panelE.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 540, 36));

        jButton11.putClientProperty(FlatClientProperties.STYLE, "arc: 10; background: #3276c3; foreground: #ffffff;");
        jButton11.setIcon(new FlatSVGIcon("icons/img-upload.svg", 20, 20)
        );
        jButton11.setText("Xem ảnh");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        panelE.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 34, -1, -1));

        jRadioButton5.setText("Đáp án đúng");
        jRadioButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        panelE.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 1, -1, -1));
        jRadioButton5.setEnabled(false);

        hinhE.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        panelE.add(hinhE, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 40, 252, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadDetailQuestion1() {
        QuestionDTO q =  question;
        
//        TopicDTO tp = tBUS.findOne(question.getQTopic());
        
        ArrayList<AnswerDTO> listA = listAnswer;

        ArrayList<TopicDTO> listTp = tBUS.getAllParentTopics(q.getQTopic());
        
        if (listTp.size() == 3) {
            monhocCBB.addItem(listTp.get(2).getTpTitle());
            chudeCBB.addItem(listTp.get(1).getTpTitle());
            baihocCBB.addItem(listTp.get(0).getTpTitle());
        }
        else if (listTp.size() == 2) {
            monhocCBB.addItem(listTp.get(1).getTpTitle());
            chudeCBB.addItem(listTp.get(0).getTpTitle());
        }
        else monhocCBB.addItem(listTp.get(0).getTpTitle());
        
        macauhoi.setText(q.getQID()+"");
        baihocCBB2.addItem(q.getQLevel());
        tenhinh.setText(q.getQPictures());
        noidung.setText(q.getQContent());
        
        
        for (int i = 0; i < listA.size(); i++) {
            listTextArea.get(i).setText(listA.get(i).getAwContent());
            listRBtn.get(i).setSelected(listA.get(i).isIsRight());
            if (listA.get(i).isIsRight()) {
                List<JPanel> panels = Arrays.asList(panelA, panelB, panelC, panelD, panelE);
                resetPanelColors(panels);  // Đặt lại màu tất cả panel trước khi đổi màu
                listPanel.get(i).putClientProperty(FlatClientProperties.STYLE, "arc: 10; background: #aaf697;");
            }
            listLabel.get(i).setText(listA.get(i).getAwPicture());
        }
        
    }
    
    
    private void loadDetailQuestion() {
        QuestionDTO q =  qBUS.findOne(qID);
        
//        TopicDTO tp = tBUS.findOne(q.getQTopic());
        
        ArrayList<AnswerDTO> listA = aBUS.getByQuesID(qID);

        ArrayList<TopicDTO> listTp = tBUS.getAllParentTopics(q.getQTopic());
        if (listTp.size() == 3) {
            monhocCBB.addItem(listTp.get(2).getTpTitle());
            chudeCBB.addItem(listTp.get(1).getTpTitle());
            baihocCBB.addItem(listTp.get(0).getTpTitle());
        }
        else if (listTp.size() == 2) {
            monhocCBB.addItem(listTp.get(1).getTpTitle());
            chudeCBB.addItem(listTp.get(0).getTpTitle());
        }
        else monhocCBB.addItem(listTp.get(0).getTpTitle());
        
        macauhoi.setText(q.getQID()+"");
        baihocCBB2.addItem(q.getQLevel());
        tenhinh.setText(q.getQPictures());
        noidung.setText(q.getQContent());
        
        
        for (int i = 0; i < listA.size(); i++) {
            listTextArea.get(i).setText(listA.get(i).getAwContent());
            listRBtn.get(i).setSelected(listA.get(i).isIsRight());
            if (listA.get(i).isIsRight()) {
                List<JPanel> panels = Arrays.asList(panelA, panelB, panelC, panelD, panelE);
                resetPanelColors(panels);  // Đặt lại màu tất cả panel trước khi đổi màu
                listPanel.get(i).putClientProperty(FlatClientProperties.STYLE, "arc: 10; background: #aaf697;");
            }
            listLabel.get(i).setText(listA.get(i).getAwPicture());
        }
        
    }
    
    private void loadPrevImage(String url) {
        if (url == null || url.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Hình không tồn tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Load ảnh từ resource
        ImageIcon icon = new ImageIcon(detailQuestion.class.getResource("/images/" + url));
        Image img = icon.getImage().getScaledInstance(190, 180, Image.SCALE_SMOOTH); // Resize ảnh
        qAnh.setIcon(new ImageIcon(img));
    }
    
//    private void selectedButton(ButtonGroup buttonGroup) {
//        // Danh sách các JRadioButton
//        List<JRadioButton> radioButtons = Arrays.asList(jRadioButton1, jRadioButton2, jRadioButton3, jRadioButton4, jRadioButton5);
//
//        // Danh sách các JPanel tương ứng (panelA, panelB, panelC, panelD, panelE)
//        List<JPanel> panels = Arrays.asList(panelA, panelB, panelC, panelD, panelE);
//
//        // Map để liên kết RadioButton với Panel tương ứng
//        Map<JRadioButton, JPanel> panelMap = new HashMap<>();
//
//        for (int i = 0; i < radioButtons.size(); i++) {
//            JRadioButton radioButton = radioButtons.get(i);
//            JPanel panel = panels.get(i);
//
//            buttonGroup.add(radioButton);
//            panelMap.put(radioButton, panel);
//
//            // Bắt sự kiện khi chọn radio button
//            radioButton.addActionListener(e -> {
//                resetPanelColors(panels);  // Đặt lại màu tất cả panel trước khi đổi màu
//                panel.putClientProperty(FlatClientProperties.STYLE, "arc: 10; background: #aaf697;"); // Đổi màu panel tương ứng
//            });
//        }
//    }

// Hàm đặt lại màu tất cả các panel về mặc định
    private void resetPanelColors(List<JPanel> panels) {
        for (JPanel panel : panels) {
            panel.putClientProperty(FlatClientProperties.STYLE, "arc: 10;");
        }
    }
    
    
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void baihocCBB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baihocCBB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baihocCBB2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        loadPrevImage(hinhE.getText());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        loadPrevImage(hinhD.getText());
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        loadPrevImage(hinhC.getText());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        loadPrevImage(hinhB.getText());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        loadPrevImage(hinhA.getText());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        loadPrevImage(tenhinh.getText());
    }//GEN-LAST:event_jButton6ActionPerformed

    private void baihocCBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baihocCBBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baihocCBBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel anh;
    private javax.swing.JComboBox<String> baihocCBB;
    private javax.swing.JComboBox<String> baihocCBB2;
    private javax.swing.JComboBox<String> chudeCBB;
    private javax.swing.JTextArea dapanA;
    private javax.swing.JTextArea dapanB;
    private javax.swing.JTextArea dapanC;
    private javax.swing.JTextArea dapanD;
    private javax.swing.JTextArea dapanE;
    private javax.swing.JLabel hinhA;
    private javax.swing.JLabel hinhB;
    private javax.swing.JLabel hinhC;
    private javax.swing.JLabel hinhD;
    private javax.swing.JLabel hinhE;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel macauhoi;
    private javax.swing.JComboBox<String> monhocCBB;
    private javax.swing.JTextArea noidung;
    private javax.swing.JPanel panelA;
    private javax.swing.JPanel panelB;
    private javax.swing.JPanel panelC;
    private javax.swing.JPanel panelD;
    private javax.swing.JPanel panelE;
    private javax.swing.JLabel qAnh;
    private javax.swing.JLabel tenhinh;
    // End of variables declaration//GEN-END:variables
}
